path: data
train: synthetic_d1/train/images
val: synthetic_d1/val/images
nc: 85
names:
  0: king-tower
  1: queen-tower
  2: cannoneer-tower
  3: dagger-duchess-tower
  4: dagger-duchess-tower-bar
  5: tower-bar
  6: king-tower-bar
  7: bar
  8: bar-level
  9: clock
  10: emote
  11: elixir
  12: skeleton-king-bar
  13: ice-spirit-evolution-symbol
  14: evolution-symbol
  15: bat
  16: elixir-golem-small
  17: fire-spirit
  18: skeleton
  19: lava-pup
  20: skeleton-evolution
  21: heal-spirit
  22: phoenix-egg
  23: bat-evolution
  24: goblin
  25: minion
  26: archer
  27: ice-spirit
  28: spear-goblin
  29: bomber
  30: rascal-girl
  31: ice-spirit-evolution
  32: hog
  33: dirt
  34: mini-pekka
  35: wizard
  36: little-prince
  37: firecracker
  38: valkyrie
  39: bandit
  40: wall-breaker
  41: princess
  42: barbarian-evolution
  43: guard
  44: knight-evolution
  45: archer-evolution
  46: elite-barbarian
  47: electro-spirit
  48: bomber-evolution
  49: bomb
  50: goblin-ball
  51: axe
  52: electro-wizard
  53: mother-witch
  54: musketeer
  55: elixir-golem-mid
  56: tesla
  57: knight
  58: fireball
  59: the-log
  60: ice-wizard
  61: valkyrie-evolution
  62: dart-goblin
  63: firecracker-evolution
  64: mortar
  65: ice-golem
  66: lumberjack
  67: royal-ghost
  68: miner
  69: night-witch
  70: ram-rider
  71: golemite
  72: electro-dragon
  73: hunter
  74: mortar-evolution
  75: skeleton-dragon
  76: executioner
  77: mega-minion
  78: witch
  79: tesla-evolution
  80: cannon-cart
  81: monk
  82: padding_0
  83: padding_1
  84: padding_belong
