path: data
train: synthetic_d2/train/images
val: synthetic_d2/val/images
nc: 85
names:
  0: king-tower
  1: queen-tower
  2: cannoneer-tower
  3: dagger-duchess-tower
  4: dagger-duchess-tower-bar
  5: tower-bar
  6: king-tower-bar
  7: bar
  8: bar-level
  9: clock
  10: emote
  11: elixir
  12: skeleton-king-bar
  13: magic-archer
  14: royal-recruit-evolution
  15: battle-ram
  16: hog-rider
  17: royal-hog
  18: baby-dragon
  19: zappy
  20: fisherman
  21: cannon
  22: barbarian
  23: rascal-boy
  24: goblin-drill
  25: prince
  26: lava-hound
  27: tombstone
  28: wall-breaker-evolution
  29: barbarian-barrel
  30: golden-knight
  31: elixir-collector
  32: archer-queen
  33: battle-healer
  34: goblin-brawler
  35: goblin-barrel
  36: dark-prince
  37: phoenix-small
  38: bowler
  39: royal-recruit
  40: pekka
  41: x-bow
  42: inferno-dragon
  43: sparky
  44: rocket
  45: mega-knight
  46: skeleton-barrel
  47: phoenix-big
  48: elixir-golem-big
  49: royal-guardian
  50: barbarian-hut
  51: goblin-hut
  52: golem
  53: goblin-giant
  54: mighty-miner
  55: balloon
  56: furnace
  57: skeleton-king
  58: battle-ram-evolution
  59: inferno-tower
  60: giant
  61: bomb-tower
  62: royal-giant
  63: royal-delivery
  64: giant-snowball
  65: royal-giant-evolution
  66: flying-machine
  67: giant-skeleton
  68: electro-giant
  69: goblin-cage
  70: rage
  71: zap
  72: lightning
  73: clone
  74: freeze
  75: poison
  76: earthquake
  77: skeleton-king-skill
  78: graveyard
  79: arrows
  80: tornado
  81: padding_0
  82: padding_1
  83: padding_2
  84: padding_belong
